// Generated by gencpp from file mavlink_lora/mavlink_lora_command_land.msg
// DO NOT EDIT!


#ifndef MAVLINK_LORA_MESSAGE_MAVLINK_LORA_COMMAND_LAND_H
#define MAVLINK_LORA_MESSAGE_MAVLINK_LORA_COMMAND_LAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_lora
{
template <class ContainerAllocator>
struct mavlink_lora_command_land_
{
  typedef mavlink_lora_command_land_<ContainerAllocator> Type;

  mavlink_lora_command_land_()
    : abort_alt(0.0)
    , precision_land_mode(0.0)
    , yaw_angle(0.0)
    , lat(0.0)
    , lon(0.0)
    , altitude(0.0)  {
    }
  mavlink_lora_command_land_(const ContainerAllocator& _alloc)
    : abort_alt(0.0)
    , precision_land_mode(0.0)
    , yaw_angle(0.0)
    , lat(0.0)
    , lon(0.0)
    , altitude(0.0)  {
  (void)_alloc;
    }



   typedef double _abort_alt_type;
  _abort_alt_type abort_alt;

   typedef double _precision_land_mode_type;
  _precision_land_mode_type precision_land_mode;

   typedef double _yaw_angle_type;
  _yaw_angle_type yaw_angle;

   typedef double _lat_type;
  _lat_type lat;

   typedef double _lon_type;
  _lon_type lon;

   typedef double _altitude_type;
  _altitude_type altitude;





  typedef boost::shared_ptr< ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator> const> ConstPtr;

}; // struct mavlink_lora_command_land_

typedef ::mavlink_lora::mavlink_lora_command_land_<std::allocator<void> > mavlink_lora_command_land;

typedef boost::shared_ptr< ::mavlink_lora::mavlink_lora_command_land > mavlink_lora_command_landPtr;
typedef boost::shared_ptr< ::mavlink_lora::mavlink_lora_command_land const> mavlink_lora_command_landConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator1> & lhs, const ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator2> & rhs)
{
  return lhs.abort_alt == rhs.abort_alt &&
    lhs.precision_land_mode == rhs.precision_land_mode &&
    lhs.yaw_angle == rhs.yaw_angle &&
    lhs.lat == rhs.lat &&
    lhs.lon == rhs.lon &&
    lhs.altitude == rhs.altitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator1> & lhs, const ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavlink_lora

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2d410eebafe4da4e351aa9c74e4140f";
  }

  static const char* value(const ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2d410eebafe4da4ULL;
  static const uint64_t static_value2 = 0xe351aa9c74e4140fULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_lora/mavlink_lora_command_land";
  }

  static const char* value(const ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 abort_alt\n"
"float64 precision_land_mode\n"
"float64 yaw_angle\n"
"float64 lat\n"
"float64 lon\n"
"float64 altitude\n"
;
  }

  static const char* value(const ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.abort_alt);
      stream.next(m.precision_land_mode);
      stream.next(m.yaw_angle);
      stream.next(m.lat);
      stream.next(m.lon);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mavlink_lora_command_land_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_lora::mavlink_lora_command_land_<ContainerAllocator>& v)
  {
    s << indent << "abort_alt: ";
    Printer<double>::stream(s, indent + "  ", v.abort_alt);
    s << indent << "precision_land_mode: ";
    Printer<double>::stream(s, indent + "  ", v.precision_land_mode);
    s << indent << "yaw_angle: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_angle);
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_LORA_MESSAGE_MAVLINK_LORA_COMMAND_LAND_H
