// Generated by gencpp from file mavlink_lora/mavlink_lora_command_reposition.msg
// DO NOT EDIT!


#ifndef MAVLINK_LORA_MESSAGE_MAVLINK_LORA_COMMAND_REPOSITION_H
#define MAVLINK_LORA_MESSAGE_MAVLINK_LORA_COMMAND_REPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_lora
{
template <class ContainerAllocator>
struct mavlink_lora_command_reposition_
{
  typedef mavlink_lora_command_reposition_<ContainerAllocator> Type;

  mavlink_lora_command_reposition_()
    : ground_speed(0.0)
    , yaw_heading(0.0)
    , lat(0.0)
    , lon(0.0)
    , alt(0.0)  {
    }
  mavlink_lora_command_reposition_(const ContainerAllocator& _alloc)
    : ground_speed(0.0)
    , yaw_heading(0.0)
    , lat(0.0)
    , lon(0.0)
    , alt(0.0)  {
  (void)_alloc;
    }



   typedef double _ground_speed_type;
  _ground_speed_type ground_speed;

   typedef double _yaw_heading_type;
  _yaw_heading_type yaw_heading;

   typedef double _lat_type;
  _lat_type lat;

   typedef double _lon_type;
  _lon_type lon;

   typedef double _alt_type;
  _alt_type alt;





  typedef boost::shared_ptr< ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator> const> ConstPtr;

}; // struct mavlink_lora_command_reposition_

typedef ::mavlink_lora::mavlink_lora_command_reposition_<std::allocator<void> > mavlink_lora_command_reposition;

typedef boost::shared_ptr< ::mavlink_lora::mavlink_lora_command_reposition > mavlink_lora_command_repositionPtr;
typedef boost::shared_ptr< ::mavlink_lora::mavlink_lora_command_reposition const> mavlink_lora_command_repositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator1> & lhs, const ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator2> & rhs)
{
  return lhs.ground_speed == rhs.ground_speed &&
    lhs.yaw_heading == rhs.yaw_heading &&
    lhs.lat == rhs.lat &&
    lhs.lon == rhs.lon &&
    lhs.alt == rhs.alt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator1> & lhs, const ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavlink_lora

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79563d72b78866c926c96f14f749ab8e";
  }

  static const char* value(const ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79563d72b78866c9ULL;
  static const uint64_t static_value2 = 0x26c96f14f749ab8eULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_lora/mavlink_lora_command_reposition";
  }

  static const char* value(const ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 ground_speed\n"
"float64 yaw_heading\n"
"float64 lat\n"
"float64 lon\n"
"float64 alt\n"
;
  }

  static const char* value(const ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ground_speed);
      stream.next(m.yaw_heading);
      stream.next(m.lat);
      stream.next(m.lon);
      stream.next(m.alt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mavlink_lora_command_reposition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_lora::mavlink_lora_command_reposition_<ContainerAllocator>& v)
  {
    s << indent << "ground_speed: ";
    Printer<double>::stream(s, indent + "  ", v.ground_speed);
    s << indent << "yaw_heading: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_heading);
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    s << indent << "alt: ";
    Printer<double>::stream(s, indent + "  ", v.alt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_LORA_MESSAGE_MAVLINK_LORA_COMMAND_REPOSITION_H
