// Generated by gencpp from file mavlink_lora/mavlink_lora_statustext.msg
// DO NOT EDIT!


#ifndef MAVLINK_LORA_MESSAGE_MAVLINK_LORA_STATUSTEXT_H
#define MAVLINK_LORA_MESSAGE_MAVLINK_LORA_STATUSTEXT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_lora
{
template <class ContainerAllocator>
struct mavlink_lora_statustext_
{
  typedef mavlink_lora_statustext_<ContainerAllocator> Type;

  mavlink_lora_statustext_()
    : severity(0)
    , text()  {
    }
  mavlink_lora_statustext_(const ContainerAllocator& _alloc)
    : severity(0)
    , text(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _severity_type;
  _severity_type severity;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator> const> ConstPtr;

}; // struct mavlink_lora_statustext_

typedef ::mavlink_lora::mavlink_lora_statustext_<std::allocator<void> > mavlink_lora_statustext;

typedef boost::shared_ptr< ::mavlink_lora::mavlink_lora_statustext > mavlink_lora_statustextPtr;
typedef boost::shared_ptr< ::mavlink_lora::mavlink_lora_statustext const> mavlink_lora_statustextConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator1> & lhs, const ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator2> & rhs)
{
  return lhs.severity == rhs.severity &&
    lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator1> & lhs, const ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavlink_lora

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator> >
{
  static const char* value()
  {
    return "308abed4c40746634f6b52263735fad3";
  }

  static const char* value(const ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x308abed4c4074663ULL;
  static const uint64_t static_value2 = 0x4f6b52263735fad3ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_lora/mavlink_lora_statustext";
  }

  static const char* value(const ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 severity\n"
"string text\n"
;
  }

  static const char* value(const ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.severity);
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mavlink_lora_statustext_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_lora::mavlink_lora_statustext_<ContainerAllocator>& v)
  {
    s << indent << "severity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.severity);
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_LORA_MESSAGE_MAVLINK_LORA_STATUSTEXT_H
