# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mavlink_lora/mavlink_lora_mission_item_int.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class mavlink_lora_mission_item_int(genpy.Message):
  _md5sum = "784b321495d46ff41f0090cf7750bfb2"
  _type = "mavlink_lora/mavlink_lora_mission_item_int"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 param1
float64 param2
float64 param3
float64 param4
int32 x
int32 y
float64 z
uint16 seq
uint16 command
uint8 target_system
uint8 target_component
uint8 frame
uint8 current
uint8 autocontinue"""
  __slots__ = ['param1','param2','param3','param4','x','y','z','seq','command','target_system','target_component','frame','current','autocontinue']
  _slot_types = ['float64','float64','float64','float64','int32','int32','float64','uint16','uint16','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       param1,param2,param3,param4,x,y,z,seq,command,target_system,target_component,frame,current,autocontinue

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(mavlink_lora_mission_item_int, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.param1 is None:
        self.param1 = 0.
      if self.param2 is None:
        self.param2 = 0.
      if self.param3 is None:
        self.param3 = 0.
      if self.param4 is None:
        self.param4 = 0.
      if self.x is None:
        self.x = 0
      if self.y is None:
        self.y = 0
      if self.z is None:
        self.z = 0.
      if self.seq is None:
        self.seq = 0
      if self.command is None:
        self.command = 0
      if self.target_system is None:
        self.target_system = 0
      if self.target_component is None:
        self.target_component = 0
      if self.frame is None:
        self.frame = 0
      if self.current is None:
        self.current = 0
      if self.autocontinue is None:
        self.autocontinue = 0
    else:
      self.param1 = 0.
      self.param2 = 0.
      self.param3 = 0.
      self.param4 = 0.
      self.x = 0
      self.y = 0
      self.z = 0.
      self.seq = 0
      self.command = 0
      self.target_system = 0
      self.target_component = 0
      self.frame = 0
      self.current = 0
      self.autocontinue = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4d2id2H5B().pack(_x.param1, _x.param2, _x.param3, _x.param4, _x.x, _x.y, _x.z, _x.seq, _x.command, _x.target_system, _x.target_component, _x.frame, _x.current, _x.autocontinue))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 57
      (_x.param1, _x.param2, _x.param3, _x.param4, _x.x, _x.y, _x.z, _x.seq, _x.command, _x.target_system, _x.target_component, _x.frame, _x.current, _x.autocontinue,) = _get_struct_4d2id2H5B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4d2id2H5B().pack(_x.param1, _x.param2, _x.param3, _x.param4, _x.x, _x.y, _x.z, _x.seq, _x.command, _x.target_system, _x.target_component, _x.frame, _x.current, _x.autocontinue))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 57
      (_x.param1, _x.param2, _x.param3, _x.param4, _x.x, _x.y, _x.z, _x.seq, _x.command, _x.target_system, _x.target_component, _x.frame, _x.current, _x.autocontinue,) = _get_struct_4d2id2H5B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d2id2H5B = None
def _get_struct_4d2id2H5B():
    global _struct_4d2id2H5B
    if _struct_4d2id2H5B is None:
        _struct_4d2id2H5B = struct.Struct("<4d2id2H5B")
    return _struct_4d2id2H5B
