# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mavlink_lora/mavlink_lora_radio_status.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class mavlink_lora_radio_status(genpy.Message):
  _md5sum = "d652cc5b05559e196e4dd9ea309ddb4b"
  _type = "mavlink_lora/mavlink_lora_radio_status"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int8 rssi
int8 remrssi
uint8 txbuf
uint8 noise
uint8 remnoise
uint16 rxerrors
uint16 fixed"""
  __slots__ = ['rssi','remrssi','txbuf','noise','remnoise','rxerrors','fixed']
  _slot_types = ['int8','int8','uint8','uint8','uint8','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       rssi,remrssi,txbuf,noise,remnoise,rxerrors,fixed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(mavlink_lora_radio_status, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.rssi is None:
        self.rssi = 0
      if self.remrssi is None:
        self.remrssi = 0
      if self.txbuf is None:
        self.txbuf = 0
      if self.noise is None:
        self.noise = 0
      if self.remnoise is None:
        self.remnoise = 0
      if self.rxerrors is None:
        self.rxerrors = 0
      if self.fixed is None:
        self.fixed = 0
    else:
      self.rssi = 0
      self.remrssi = 0
      self.txbuf = 0
      self.noise = 0
      self.remnoise = 0
      self.rxerrors = 0
      self.fixed = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2b3B2H().pack(_x.rssi, _x.remrssi, _x.txbuf, _x.noise, _x.remnoise, _x.rxerrors, _x.fixed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.rssi, _x.remrssi, _x.txbuf, _x.noise, _x.remnoise, _x.rxerrors, _x.fixed,) = _get_struct_2b3B2H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2b3B2H().pack(_x.rssi, _x.remrssi, _x.txbuf, _x.noise, _x.remnoise, _x.rxerrors, _x.fixed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.rssi, _x.remrssi, _x.txbuf, _x.noise, _x.remnoise, _x.rxerrors, _x.fixed,) = _get_struct_2b3B2H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2b3B2H = None
def _get_struct_2b3B2H():
    global _struct_2b3B2H
    if _struct_2b3B2H is None:
        _struct_2b3B2H = struct.Struct("<2b3B2H")
    return _struct_2b3B2H
