(cl:in-package mavlink_lora-msg)
(cl:export '(TIME_BOOT_MS-VAL
          TIME_BOOT_MS
          TARGET_SYSTEM-VAL
          TARGET_SYSTEM
          TARGET_COMPONENT-VAL
          TARGET_COMPONENT
          COORDINATE_FRAME-VAL
          COORDINATE_FRAME
          TYPE_MASK-VAL
          TYPE_MASK
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          AFX-VAL
          AFX
          AFY-VAL
          AFY
          AFZ-VAL
          AFZ
          YAW-VAL
          YAW
          YAW_RATE-VAL
          YAW_RATE
))