(cl:in-package mavlink_lora-msg)
(cl:export '(PARAM1-VAL
          PARAM1
          PARAM2-VAL
          PARAM2
          PARAM3-VAL
          PARAM3
          PARAM4-VAL
          PARAM4
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          SEQ-VAL
          SEQ
          COMMAND-VAL
          COMMAND
          TARGET_SYSTEM-VAL
          TARGET_SYSTEM
          TARGET_COMPONENT-VAL
          TARGET_COMPONENT
          FRAME-VAL
          FRAME
          CURRENT-VAL
          CURRENT
          AUTOCONTINUE-VAL
          AUTOCONTINUE
))