
(cl:in-package :asdf)

(defsystem "mavlink_lora-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :std_msgs-msg
)
  :components ((:file "_package")
    (:file "mavlink_lora_attitude" :depends-on ("_package_mavlink_lora_attitude"))
    (:file "_package_mavlink_lora_attitude" :depends-on ("_package"))
    (:file "mavlink_lora_command_ack" :depends-on ("_package_mavlink_lora_command_ack"))
    (:file "_package_mavlink_lora_command_ack" :depends-on ("_package"))
    (:file "mavlink_lora_command_land" :depends-on ("_package_mavlink_lora_command_land"))
    (:file "_package_mavlink_lora_command_land" :depends-on ("_package"))
    (:file "mavlink_lora_command_reposition" :depends-on ("_package_mavlink_lora_command_reposition"))
    (:file "_package_mavlink_lora_command_reposition" :depends-on ("_package"))
    (:file "mavlink_lora_command_set_mode" :depends-on ("_package_mavlink_lora_command_set_mode"))
    (:file "_package_mavlink_lora_command_set_mode" :depends-on ("_package"))
    (:file "mavlink_lora_command_start_mission" :depends-on ("_package_mavlink_lora_command_start_mission"))
    (:file "_package_mavlink_lora_command_start_mission" :depends-on ("_package"))
    (:file "mavlink_lora_command_takeoff" :depends-on ("_package_mavlink_lora_command_takeoff"))
    (:file "_package_mavlink_lora_command_takeoff" :depends-on ("_package"))
    (:file "mavlink_lora_enable_offboard" :depends-on ("_package_mavlink_lora_enable_offboard"))
    (:file "_package_mavlink_lora_enable_offboard" :depends-on ("_package"))
    (:file "mavlink_lora_gps_raw" :depends-on ("_package_mavlink_lora_gps_raw"))
    (:file "_package_mavlink_lora_gps_raw" :depends-on ("_package"))
    (:file "mavlink_lora_heartbeat" :depends-on ("_package_mavlink_lora_heartbeat"))
    (:file "_package_mavlink_lora_heartbeat" :depends-on ("_package"))
    (:file "mavlink_lora_mission_ack" :depends-on ("_package_mavlink_lora_mission_ack"))
    (:file "_package_mavlink_lora_mission_ack" :depends-on ("_package"))
    (:file "mavlink_lora_mission_item_int" :depends-on ("_package_mavlink_lora_mission_item_int"))
    (:file "_package_mavlink_lora_mission_item_int" :depends-on ("_package"))
    (:file "mavlink_lora_mission_list" :depends-on ("_package_mavlink_lora_mission_list"))
    (:file "_package_mavlink_lora_mission_list" :depends-on ("_package"))
    (:file "mavlink_lora_msg" :depends-on ("_package_mavlink_lora_msg"))
    (:file "_package_mavlink_lora_msg" :depends-on ("_package"))
    (:file "mavlink_lora_pos" :depends-on ("_package_mavlink_lora_pos"))
    (:file "_package_mavlink_lora_pos" :depends-on ("_package"))
    (:file "mavlink_lora_radio_status" :depends-on ("_package_mavlink_lora_radio_status"))
    (:file "_package_mavlink_lora_radio_status" :depends-on ("_package"))
    (:file "mavlink_lora_set_position_target_local_ned" :depends-on ("_package_mavlink_lora_set_position_target_local_ned"))
    (:file "_package_mavlink_lora_set_position_target_local_ned" :depends-on ("_package"))
    (:file "mavlink_lora_status" :depends-on ("_package_mavlink_lora_status"))
    (:file "_package_mavlink_lora_status" :depends-on ("_package"))
    (:file "mavlink_lora_statustext" :depends-on ("_package_mavlink_lora_statustext"))
    (:file "_package_mavlink_lora_statustext" :depends-on ("_package"))
  ))